[tool.poetry]
name = "mediabot"
version = "0.1.0"
description = ""
authors = ["Fabio <fabio.manzoni@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
